### ISSUE TITLE
Update Everything

### ISSUE THREAD

**Issue by organelleV** [Robotiators-888/2023Season#1]
New versions of software have been released for the 2023 season, and many things must be updated.

Install the new version of Wpilib from here:
https://github.com/wpilibsuite/allwpilib/releases

Robot will need to be flashed with new RoboRIO image:
https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-3/imaging-your-roborio.html
https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-3/roborio2-imaging.html

**Comment by Spenceroni-Pepperoni** [comment]
Alpha and Desktop needs to have WPILIB updated as well as Phoenix tuner and Rev hardware client.
